site_name: SlopeCraft 文档
docs_dir: 'docs'
repo_url: https://github.com/SlopeCraft/SlopeCraftDocs
repo_name: SlopeCraft/SlopeCraftDocs
edit_uri: edit/main/docs/

site_author: SlopeCraft Team, Cubik65536, ToKiNoBug and Contributors
copyright: Copyright © 2023 SlopeCraft Team, Cubik65536, ToKiNoBug and Contributors. 
  All rights reserved.<br/>
  Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs

# Customization
extra_css:
  - '_static/css/extra.css?v=14'
  
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - footnotes

# Navigation
nav:
  - 欢迎使用 SlopeCraft: index.md
  - VisualCraft 教程: VisualCraft-tutorial.md
  - SlopeCraft 教程: SlopeCraft-tutorial.md

# Plugins
plugins:
  - search
  - i18n:
      default_language: zh
      docs_structure: suffix
      languages:
        zh:
          name: 中文
          site_name: SlopeCraft 文档
          build: false
        en:
          name: English
          site_name: SlopeCraft Documentation
          build: true
      nav_translations:
        en:
          欢迎使用 SlopeCraft: Welcome to SlopeCraft
          VisualCraft 教程: VisualCraft Tutorial
          SlopeCraft 教程: SlopeCraft Tutorial
